"""Generate the configuration reference in docs/configuration.md from the code.

Sources: the argparse parsers of the console scripts, module constants, the notes server
tool registry, policy.SCHEMA and deploy/policy.yaml. Output is deterministic: no timestamps, no
terminal-width dependent help text.

Usage:
    uv run python scripts/gen_config_docs.py            print the generated block
    uv run python scripts/gen_config_docs.py --write    update docs/configuration.md
    uv run python scripts/gen_config_docs.py --check    exit 1 with a diff on drift
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import yaml

from mcp_svid_auth import agent_client, audit, authz, mcp_server, spiffe_keys, stdio_wrapper
from mcp_svid_auth.policy import SCHEMA, Policy

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "configuration.md"
POLICY_EXAMPLE = ROOT / "deploy" / "policy.yaml"
BEGIN = "<!-- BEGIN GENERATED: config -->"
END = "<!-- END GENERATED: config -->"


def _cell(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def _flag(action: argparse.Action) -> str:
    if action.option_strings:
        return ", ".join(f"`{s}`" for s in action.option_strings)
    if action.nargs == argparse.REMAINDER:
        return f"`-- {action.dest} [args...]`"
    return f"`{action.dest}`"


def _default(action: argparse.Action) -> str:
    if action.required or action.nargs == argparse.REMAINDER:
        return "required"
    if action.nargs == 0 and action.const is True:
        return "off"
    if action.default is None:
        return "none"
    return f"`{action.default}`"


def _meaning(action: argparse.Action) -> str:
    text = action.help or ""
    return _cell(text[:1].upper() + text[1:])


def _table(header: tuple[str, ...], rows: Sequence[tuple[str, ...]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return lines


def _command(parser: argparse.ArgumentParser, fixed: list[tuple[str, str]]) -> list[str]:
    rows = [
        (_flag(a), _default(a), _meaning(a))
        for a in parser._actions
        if not isinstance(a, argparse._HelpAction)
    ]
    out = [f"## `{parser.prog}`", "", _cell(parser.description or ""), ""]
    out += _table(("Flag", "Default", "Meaning"), rows)
    if fixed:
        out += ["", "Fixed values:", ""]
        out += _table(("Setting", "Value"), fixed)
    return [*out, ""]


def _key_paths(data: Any, prefix: str = "") -> set[str]:
    paths: set[str] = set()
    if not isinstance(data, dict):
        return paths
    for key, value in data.items():
        path = f"{prefix}{key}"
        paths.add(path)
        if isinstance(value, list):
            for item in value:
                paths |= _key_paths(item, f"{path}[].")
    return paths


def _policy() -> list[str]:
    example = POLICY_EXAMPLE.read_text(encoding="utf-8")
    Policy.load(POLICY_EXAMPLE)
    documented = {path for path, _, _ in SCHEMA}
    used = _key_paths(yaml.safe_load(example))
    if used != documented:
        raise SystemExit(
            f"policy.SCHEMA and {POLICY_EXAMPLE.relative_to(ROOT)} disagree: "
            f"undocumented {sorted(used - documented)}, unused {sorted(documented - used)}"
        )
    out = [
        "## Policy file",
        "",
        f"Example from `{POLICY_EXAMPLE.relative_to(ROOT)}`:",
        "",
        "```yaml",
        example.rstrip("\n"),
        "```",
        "",
    ]
    out += _table(("Key", "Type", "Meaning"), [(f"`{p}`", t, _cell(m)) for p, t, m in SCHEMA])
    return [*out, ""]


def generate() -> str:
    _, tool_scopes = mcp_server.build_mcp("notes", mcp_server.NotesStore())
    tools = ", ".join(f"`{t}` (`{s}`)" for t, s in sorted(tool_scopes.items()))
    lines = [
        "<!-- Generated by scripts/gen_config_docs.py. Do not edit by hand. -->",
        "",
    ]
    lines += _command(
        authz.build_parser(),
        [
            ("Access token TTL", f"{authz.DEFAULT_TOKEN_TTL}s"),
            ("Access token algorithm", f"`{authz.ACCESS_TOKEN_ALG}`"),
            ("SVID clock leeway", f"{authz._CLOCK_SKEW}s"),
            ("Trust bundle cache (Workload API)", f"{spiffe_keys._BUNDLE_CACHE_SECONDS}s"),
        ],
    )
    lines += _command(
        mcp_server.build_parser(),
        [
            ("Tools (scope)", tools),
            ("JWKS cache", f"{mcp_server.JWKS_CACHE_SECONDS}s"),
            ("Unknown `kid` refetch", f"at most every {mcp_server.JWKS_MIN_REFETCH_SECONDS}s"),
            ("Request body limit", f"{mcp_server.MAX_BODY_BYTES} bytes"),
            ("Accepted token `typ`", f"`{mcp_server._ACCESS_TOKEN_TYP}`"),
            (
                "Accepted token algorithms",
                ", ".join(f"`{a}`" for a in mcp_server._ACCESS_TOKEN_ALGS),
            ),
        ],
    )
    lines += _command(agent_client.build_parser(), [])
    lines += _command(
        stdio_wrapper.build_parser(),
        [
            ("Exit code when the token cannot be refreshed", str(stdio_wrapper.EXIT_TOKEN_EXPIRED)),
            (
                "Grace between SIGTERM and SIGKILL for the child on expiry",
                f"{stdio_wrapper.KILL_GRACE_SECONDS:g}s",
            ),
        ],
    )
    lines += _command(
        audit.build_parser(),
        [("Chain", "`prev_hash` = SHA-256 of the JCS form of the previous record, hex")],
    )
    lines += _policy()
    return "\n".join(lines).rstrip("\n") + "\n"


def render(current: str) -> str:
    if current.count(BEGIN) != 1 or current.count(END) != 1:
        raise SystemExit(f"{DOC.relative_to(ROOT)}: expected exactly one {BEGIN} and one {END}")
    head, rest = current.split(BEGIN)
    _, tail = rest.split(END)
    return f"{head}{BEGIN}\n{generate()}{END}{tail}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="update the doc in place")
    mode.add_argument("--check", action="store_true", help="exit 1 with a diff on drift")
    args = parser.parse_args(argv)

    if not (args.write or args.check):
        sys.stdout.write(generate())
        return 0
    current = DOC.read_text(encoding="utf-8")
    expected = render(current)
    if args.write:
        if expected != current:
            DOC.write_text(expected, encoding="utf-8")
        return 0
    if expected == current:
        return 0
    name = str(DOC.relative_to(ROOT))
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{name} (committed)",
        tofile=f"{name} (generated)",
    )
    sys.stdout.writelines(diff)
    sys.stdout.write(
        f"\n{name} is out of date. Run: uv run python scripts/gen_config_docs.py --write\n"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
